using System.Security;
using System.Text;
using MyFhirSdk.CodeGen.Models;

namespace MyFhirSdk.CodeGen.Rendering;

public sealed class CSharpClassRenderer
{
    private const char LineFeed = '\n';

    public string Render(FhirTypeModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        var properties = model.Properties
            .OrderBy(property => property.Order)
            .ThenBy(property => property.CSharpName, StringComparer.Ordinal)
            .ToArray();
        var namespaces = GetRequiredNamespaces(model, properties);
        var source = new StringBuilder();

        AppendLine(source, "// <auto-generated />");
        AppendLine(source, "#nullable enable");
        AppendLine(source);

        foreach (var requiredNamespace in namespaces)
        {
            AppendLine(source, $"using {requiredNamespace};");
        }

        if (namespaces.Count > 0)
        {
            AppendLine(source);
        }

        AppendLine(source, $"namespace {model.Namespace};");
        AppendLine(source);
        AppendSummary(
            source,
            "Human-readable definition from StructureDefinition.");

        var classModifier = model.IsAbstract ? "abstract" : "sealed";
        var baseType = GetUnqualifiedTypeName(model.CSharpBaseType);
        AppendLine(
            source,
            $"public {classModifier} class {model.CSharpName} : {baseType}");
        AppendLine(source, "{");

        for (var index = 0; index < properties.Length; index++)
        {
            RenderProperty(source, properties[index]);
            if (index < properties.Length - 1)
            {
                AppendLine(source);
            }
        }

        AppendLine(source, "}");
        return source.ToString();
    }

    private static IReadOnlyList<string> GetRequiredNamespaces(
        FhirTypeModel model,
        IEnumerable<FhirPropertyModel> properties)
    {
        var namespaces = new HashSet<string>(StringComparer.Ordinal);

        if (properties.Any(property => property.IsCollection))
        {
            namespaces.Add("System.Collections.Generic");
        }

        AddTypeNamespace(namespaces, model.CSharpBaseType, model.Namespace);
        foreach (var property in properties)
        {
            AddTypeNamespace(namespaces, property.CSharpType, model.Namespace);
        }

        return namespaces
            .OrderBy(
                requiredNamespace => requiredNamespace.StartsWith(
                    "System.",
                    StringComparison.Ordinal)
                        ? 0
                        : 1)
            .ThenBy(requiredNamespace => requiredNamespace, StringComparer.Ordinal)
            .ToArray();
    }

    private static void AddTypeNamespace(
        ISet<string> namespaces,
        string cSharpType,
        string targetNamespace)
    {
        var separatorIndex = cSharpType.LastIndexOf('.');
        if (separatorIndex <= 0)
        {
            return;
        }

        var typeNamespace = cSharpType[..separatorIndex];
        if (!string.Equals(
                typeNamespace,
                targetNamespace,
                StringComparison.Ordinal))
        {
            namespaces.Add(typeNamespace);
        }
    }

    private static void RenderProperty(
        StringBuilder source,
        FhirPropertyModel property)
    {
        if (!string.IsNullOrWhiteSpace(property.Documentation))
        {
            AppendSummary(source, property.Documentation, indentation: "    ");
        }

        var propertyType = GetUnqualifiedTypeName(property.CSharpType);
        if (property.IsCollection)
        {
            AppendLine(
                source,
                $"    public IList<{propertyType}> {property.CSharpName} " +
                $"{{ get; set; }} = new List<{propertyType}>();");
            return;
        }

        AppendLine(
            source,
            $"    public {propertyType}? {property.CSharpName} {{ get; set; }}");
    }

    private static string GetUnqualifiedTypeName(string cSharpType)
    {
        var separatorIndex = cSharpType.LastIndexOf('.');
        return separatorIndex < 0
            ? cSharpType
            : cSharpType[(separatorIndex + 1)..];
    }

    private static void AppendSummary(
        StringBuilder source,
        string documentation,
        string indentation = "")
    {
        AppendLine(source, $"{indentation}/// <summary>");

        var escapedDocumentation = SecurityElement.Escape(documentation) ?? "";
        foreach (var line in NormalizeNewlines(escapedDocumentation).Split(LineFeed))
        {
            AppendLine(source, $"{indentation}/// {line}");
        }

        AppendLine(source, $"{indentation}/// </summary>");
    }

    private static string NormalizeNewlines(string value)
    {
        return value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', LineFeed);
    }

    private static void AppendLine(StringBuilder source, string value = "")
    {
        source.Append(value);
        source.Append(LineFeed);
    }
}
