using System.Text;
using MyFhirSdk.CodeGen.Metadata;

namespace MyFhirSdk.CodeGen.Rendering;

public sealed class ModelMetadataRenderer
{
    public const string ArtifactPath = "Generated/R5/ModelMetadata/R5ModelMetadata.g.cs";

    public string Render(ModelMetadataIrBatch metadata)
    {
        ArgumentNullException.ThrowIfNull(metadata);
        var source = new StringBuilder();
        AppendLine(source, "// <auto-generated />");
        AppendLine(source, "#nullable enable");
        AppendLine(source);
        AppendLine(source, "namespace MyFhirSdk.ModelMetadata.R5;");
        AppendLine(source);
        AppendLine(source, "internal static class GeneratedR5ModelMetadata");
        AppendLine(source, "{");
        AppendLine(source, "    internal static global::MyFhirSdk.ModelMetadata.ImmutableModelMetadataProvider Create() =>");
        AppendLine(source, "        new(");
        RenderResources(source, metadata.Resources);
        RenderDatatypes(source, metadata.ConcreteDatatypes);
        RenderDeclaredDatatypes(source, metadata.DeclaredDatatypes);
        RenderExtensionValues(source, metadata.ExtensionValues);
        RenderOpenTypes(source, metadata.OpenTypes);
        AppendLine(source, "        );");
        AppendLine(source, "}");
        return source.ToString();
    }

    private static void RenderDeclaredDatatypes(
        StringBuilder source,
        IReadOnlyList<DeclaredDatatypeMetadataIr> datatypes)
    {
        AppendLine(source, "            new global::MyFhirSdk.ModelMetadata.DeclaredDataTypeMetadata[]");
        AppendLine(source, "            {");
        foreach (var datatype in datatypes)
        {
            AppendLine(source, "                new(");
            AppendLine(source, $"                    typeof({TypeName(datatype.DeclaringClrType)}),");
            AppendLine(source, $"                    \"{Escape(datatype.PropertyName)}\",");
            AppendLine(source, $"                    typeof({TypeName(datatype.ConcreteClrType)})),");
        }
        AppendLine(source, "            },");
    }

    private static void RenderResources(
        StringBuilder source,
        IReadOnlyList<ResourceFactoryMetadataIr> resources)
    {
        AppendLine(source, "            new global::MyFhirSdk.ModelMetadata.ResourceTypeMetadata[]");
        AppendLine(source, "            {");
        foreach (var resource in resources)
        {
            AppendLine(source, "                new(");
            AppendLine(source, $"                    \"{Escape(resource.FhirTypeName)}\",");
            AppendLine(source, $"                    typeof({TypeName(resource.ClrType)}),");
            AppendLine(source, $"                    static () => new {TypeName(resource.ClrType)}()),");
        }
        AppendLine(source, "            },");
    }

    private static void RenderDatatypes(
        StringBuilder source,
        IReadOnlyList<ConcreteDatatypeMetadataIr> datatypes)
    {
        AppendLine(source, "            new global::System.Type[]");
        AppendLine(source, "            {");
        foreach (var datatype in datatypes)
        {
            AppendLine(source, $"                typeof({TypeName(datatype.ClrType)}),");
        }
        AppendLine(source, "            },");
    }

    private static void RenderExtensionValues(
        StringBuilder source,
        IReadOnlyList<ExtensionValueMetadataIr> values)
    {
        AppendLine(source, "            new global::MyFhirSdk.ModelMetadata.ExtensionValueMetadata[]");
        AppendLine(source, "            {");
        foreach (var value in values)
        {
            AppendLine(source, "                new(");
            AppendLine(source, $"                    typeof({TypeName(value.ClrType)}),");
            AppendLine(source, $"                    \"{Escape(value.JsonPropertyName)}\"),");
        }
        AppendLine(source, "            },");
    }

    private static void RenderOpenTypes(
        StringBuilder source,
        IReadOnlyList<OpenTypeMetadataIr> values)
    {
        AppendLine(source, "            new global::MyFhirSdk.ModelMetadata.OpenTypeValueMetadata[]");
        AppendLine(source, "            {");
        foreach (var value in values)
        {
            AppendLine(source, "                new(");
            AppendLine(source, $"                    typeof({TypeName(value.DeclaringClrType)}),");
            AppendLine(source, $"                    \"{Escape(value.ClrPropertyName)}\",");
            AppendLine(source, $"                    typeof({TypeName(value.ValueClrType)}),");
            AppendLine(source, $"                    \"{Escape(value.JsonPropertyName)}\"),");
        }
        AppendLine(source, "            }");
    }

    private static string TypeName(string clrType) => "global::" + clrType;

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static void AppendLine(StringBuilder source, string value = "") =>
        source.Append(value).Append('\n');
}
