using System.Security;
using System.Text;
using MyFhirSdk.CodeGen.Ir;

namespace MyFhirSdk.CodeGen.Rendering;

internal sealed class ModelDeclarationSourceRenderer
{
    private const char LineFeed = '\n';

    public string Render(
        ModelDeclarationIr declaration,
        string summary,
        string? resourceType = null)
    {
        ArgumentNullException.ThrowIfNull(declaration);
        if (string.IsNullOrWhiteSpace(declaration.BaseType.ClrType))
        {
            throw new ArgumentException(
                $"Model declaration '{declaration.FullyQualifiedName}' has no CLR base type.",
                nameof(declaration));
        }

        var memberProperties = declaration.Members
            .OrderBy(member => member.Order)
            .SelectMany(member => member.Properties.Select(property => (Member: member, Property: property)))
            .ToArray();
        if (memberProperties.Any(item => string.IsNullOrWhiteSpace(item.Property.CSharpType)))
        {
            throw new ArgumentException(
                $"Model declaration '{declaration.FullyQualifiedName}' has an unresolved property CLR type.",
                nameof(declaration));
        }

        var properties = memberProperties.Select(item => item.Property).ToArray();
        var source = new StringBuilder();
        var requiredNamespaces = GetRequiredNamespaces(declaration, properties, resourceType is not null);
        AppendLine(source, "// <auto-generated />");
        AppendLine(source, "#nullable enable");
        AppendLine(source);
        foreach (var requiredNamespace in requiredNamespaces)
        {
            AppendLine(source, $"using {requiredNamespace};");
        }
        if (requiredNamespaces.Count > 0)
        {
            AppendLine(source);
        }

        AppendLine(source, $"namespace {declaration.Namespace};");
        AppendLine(source);
        AppendSummary(source, summary);
        var modifier = declaration.IsAbstract
            ? "abstract "
            : declaration.IsSealed
                ? "sealed "
                : string.Empty;
        AppendLine(
            source,
            $"public {modifier}class {declaration.CSharpName} : {Unqualified(declaration.BaseType.ClrType)}");
        AppendLine(source, "{");

        if (resourceType is not null)
        {
            AppendLine(source, "    /// <inheritdoc />");
            AppendLine(source, "    [JsonPropertyName(\"resourceType\")]");
            AppendLine(
                source,
                $"    public override string ResourceType => \"{EscapeStringLiteral(resourceType)}\";");
            if (memberProperties.Length > 0)
            {
                AppendLine(source);
            }
        }

        for (var index = 0; index < memberProperties.Length; index++)
        {
            RenderProperty(source, memberProperties[index].Member, memberProperties[index].Property);
            if (index < memberProperties.Length - 1)
            {
                AppendLine(source);
            }
        }
        AppendLine(source, "}");
        return source.ToString();
    }

    private static IReadOnlyList<string> GetRequiredNamespaces(
        ModelDeclarationIr declaration,
        IEnumerable<ModelPropertyIr> properties,
        bool hasResourceType)
    {
        var namespaces = new HashSet<string>(StringComparer.Ordinal);
        var propertyArray = properties.ToArray();
        if (propertyArray.Any(property => property.IsCollection))
        {
            namespaces.Add("System.Collections.Generic");
        }
        if (hasResourceType || propertyArray.Any(RequiresJsonNameAttribute))
        {
            namespaces.Add("System.Text.Json.Serialization");
        }
        AddTypeNamespace(namespaces, declaration.BaseType.ClrType!, declaration.Namespace);
        foreach (var property in propertyArray)
        {
            AddTypeNamespace(namespaces, property.CSharpType!, declaration.Namespace);
        }
        return namespaces
            .OrderBy(value => value.StartsWith("System.", StringComparison.Ordinal) ? 0 : 1)
            .ThenBy(value => value, StringComparer.Ordinal)
            .ToArray();
    }

    private static void RenderProperty(
        StringBuilder source,
        ModelMemberIr member,
        ModelPropertyIr property)
    {
        if (!string.IsNullOrWhiteSpace(member.Documentation))
        {
            AppendSummary(source, member.Documentation, "    ");
        }
        if (RequiresJsonNameAttribute(property))
        {
            AppendLine(
                source,
                $"    [JsonPropertyName(\"{EscapeStringLiteral(property.JsonName)}\")]");
        }

        var typeName = Unqualified(property.CSharpType!);
        if (property.IsCollection)
        {
            AppendLine(
                source,
                $"    public IList<{typeName}> {property.CSharpName} {{ get; set; }} = new List<{typeName}>();");
            return;
        }
        var nullableSuffix = property.IsNullable ? "?" : string.Empty;
        AppendLine(
            source,
            $"    public {typeName}{nullableSuffix} {property.CSharpName} {{ get; set; }}");
    }

    private static bool RequiresJsonNameAttribute(ModelPropertyIr property) =>
        !string.Equals(property.JsonName, ToCamelCase(property.CSharpName), StringComparison.Ordinal);

    private static string ToCamelCase(string value) =>
        string.IsNullOrEmpty(value) || char.IsLower(value[0])
            ? value
            : char.ToLowerInvariant(value[0]) + value[1..];

    private static string EscapeStringLiteral(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static void AddTypeNamespace(
        ISet<string> namespaces,
        string cSharpType,
        string declarationNamespace)
    {
        var separator = cSharpType.LastIndexOf('.');
        if (separator <= 0)
        {
            return;
        }
        var targetNamespace = cSharpType[..separator];
        if (!string.Equals(targetNamespace, declarationNamespace, StringComparison.Ordinal))
        {
            namespaces.Add(targetNamespace);
        }
    }

    private static string Unqualified(string cSharpType)
    {
        var separator = cSharpType.LastIndexOf('.');
        return separator < 0 ? cSharpType : cSharpType[(separator + 1)..];
    }

    private static void AppendSummary(
        StringBuilder source,
        string documentation,
        string indentation = "")
    {
        AppendLine(source, $"{indentation}/// <summary>");
        var escaped = SecurityElement.Escape(documentation) ?? string.Empty;
        foreach (var line in NormalizeNewlines(escaped).Split(LineFeed))
        {
            AppendLine(source, $"{indentation}/// {line}");
        }
        AppendLine(source, $"{indentation}/// </summary>");
    }

    private static string NormalizeNewlines(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', LineFeed);

    private static void AppendLine(StringBuilder source, string value = "")
    {
        source.Append(value);
        source.Append(LineFeed);
    }
}
