using System.Globalization;
using System.Security;
using System.Text;
using MyFhirSdk.CodeGen.Compilation;
using MyFhirSdk.CodeGen.Models;

namespace MyFhirSdk.CodeGen.Rendering;

public sealed class PrimitiveWrapperRenderer
{
    private const char LineFeed = '\n';

    public string Render(PrimitiveWrapperModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        var source = new StringBuilder();
        AppendLine(source, "// <auto-generated />");
        AppendLine(source, "#nullable enable");
        AppendLine(source);

        if (RequiresGlobalization(model))
        {
            AppendLine(source, "using System.Globalization;");
        }

        AppendLine(source, "using MyFhirSdk.Core;");
        AppendLine(source);
        AppendLine(source, $"namespace {model.Namespace};");
        AppendLine(source);
        AppendSummary(source, model.Documentation);
        AppendLine(
            source,
            $"public sealed class {model.WrapperName} : " +
            $"PrimitiveType<{model.ClrValueType}>");
        AppendLine(source, "{");

        RenderConstants(source, model.PublicConstants);
        if (model.PublicConstants.Count > 0)
        {
            AppendLine(source);
        }

        AppendLine(source, $"    public {model.WrapperName}()");
        AppendLine(source, "    {");
        AppendLine(source, "    }");
        AppendLine(source);

        AppendLine(
            source,
            $"    public {model.WrapperName}(" +
            $"{GetConstructorValueType(model.ClrValueType)} value)");
        AppendLine(source, "        : base(value)");
        AppendLine(source, "    {");
        AppendLine(source, "    }");

        if (model.LiteralKind != PrimitiveWrapperLiteralKind.None)
        {
            AppendLine(source);
            RenderLiteralConstructor(source, model);
            AppendLine(source);
            RenderLiteralProperty(source, model);
        }

        if (model.ToStringKind != PrimitiveWrapperToStringKind.Inherited)
        {
            AppendLine(source);
            RenderToString(source, model);
        }

        AppendLine(source, "}");
        return source.ToString();
    }

    public IReadOnlyList<GeneratedSource> RenderAll(
        IEnumerable<PrimitiveWrapperModel> models)
    {
        ArgumentNullException.ThrowIfNull(models);

        var materialized = models.ToArray();
        foreach (var model in materialized)
        {
            ArgumentNullException.ThrowIfNull(model);
        }

        var duplicateFileName = materialized
            .GroupBy(model => model.FileName, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .OrderBy(group => group.Key, StringComparer.Ordinal)
            .Select(group => group.Key)
            .FirstOrDefault();
        if (duplicateFileName is not null)
        {
            throw new ArgumentException(
                $"Primitive wrapper output file name '{duplicateFileName}' is " +
                "duplicated.",
                nameof(models));
        }

        return Array.AsReadOnly(materialized
            .OrderBy(model => model.FileName, StringComparer.Ordinal)
            .Select(model => new GeneratedSource(model.FileName, Render(model)))
            .ToArray());
    }

    private static void RenderConstants(
        StringBuilder source,
        IEnumerable<PrimitiveWrapperConstantModel> constants)
    {
        foreach (var constant in constants.OrderBy(
                     item => item.Name,
                     StringComparer.Ordinal))
        {
            var typeName = constant.ClrType switch
            {
                PrimitiveWrapperConstantClrType.Int32 => "int",
                PrimitiveWrapperConstantClrType.Int64 => "long",
                _ => throw new InvalidOperationException(
                    $"Unsupported primitive constant CLR type " +
                    $"'{constant.ClrType}'.")
            };
            var suffix = constant.ClrType == PrimitiveWrapperConstantClrType.Int64
                ? "L"
                : "";
            AppendLine(
                source,
                $"    public const {typeName} {constant.Name} = " +
                $"{constant.Value.ToString(CultureInfo.InvariantCulture)}{suffix};");
        }
    }

    private static void RenderLiteralConstructor(
        StringBuilder source,
        PrimitiveWrapperModel model)
    {
        AppendLine(
            source,
            $"    public {model.WrapperName}(string? value)");
        AppendLine(source, "    {");
        AppendLine(source, $"        {model.LiteralPropertyName} = value;");
        AppendLine(source);
        AppendLine(source, "        if (value is not null &&");

        switch (model.LiteralKind)
        {
            case PrimitiveWrapperLiteralKind.Decimal:
                AppendLine(source, "            decimal.TryParse(");
                AppendLine(source, "                value,");
                AppendLine(source, "                NumberStyles.Float,");
                break;
            case PrimitiveWrapperLiteralKind.Integer64:
                AppendLine(source, "            long.TryParse(");
                AppendLine(source, "                value,");
                AppendLine(source, "                NumberStyles.AllowLeadingSign,");
                break;
            default:
                throw new InvalidOperationException(
                    $"Unsupported primitive literal kind '{model.LiteralKind}'.");
        }

        AppendLine(source, "                CultureInfo.InvariantCulture,");
        AppendLine(source, "                out var parsedValue))");
        AppendLine(source, "        {");
        AppendLine(source, "            Value = parsedValue;");
        AppendLine(source, "        }");
        AppendLine(source, "    }");
    }

    private static void RenderLiteralProperty(
        StringBuilder source,
        PrimitiveWrapperModel model)
    {
        AppendSummary(
            source,
            $"Original FHIR {model.FhirTypeName} literal when the value was " +
            "created from text.",
            "    ");
        AppendLine(
            source,
            $"    public string? {model.LiteralPropertyName} {{ get; }}");
    }

    private static void RenderToString(
        StringBuilder source,
        PrimitiveWrapperModel model)
    {
        AppendLine(source, "    public override string ToString()");
        AppendLine(source, "    {");

        var returnExpression = model.ToStringKind switch
        {
            PrimitiveWrapperToStringKind.BooleanLowercase =>
                "Value?.ToString().ToLowerInvariant() ?? string.Empty",
            PrimitiveWrapperToStringKind.InvariantValue =>
                "Value?.ToString(CultureInfo.InvariantCulture) ?? string.Empty",
            PrimitiveWrapperToStringKind.LiteralOrInvariantValue =>
                $"{model.LiteralPropertyName} ?? " +
                "Value?.ToString(CultureInfo.InvariantCulture) ?? string.Empty",
            _ => throw new InvalidOperationException(
                $"Unsupported primitive ToString kind '{model.ToStringKind}'.")
        };

        AppendLine(source, $"        return {returnExpression};");
        AppendLine(source, "    }");
    }

    private static bool RequiresGlobalization(PrimitiveWrapperModel model)
    {
        return model.LiteralKind != PrimitiveWrapperLiteralKind.None ||
            model.ToStringKind is
                PrimitiveWrapperToStringKind.InvariantValue or
                PrimitiveWrapperToStringKind.LiteralOrInvariantValue;
    }

    private static string GetConstructorValueType(string clrValueType)
    {
        return clrValueType.EndsWith("?", StringComparison.Ordinal)
            ? clrValueType
            : $"{clrValueType}?";
    }

    private static void AppendSummary(
        StringBuilder source,
        string documentation,
        string indentation = "")
    {
        AppendLine(source, $"{indentation}/// <summary>");
        var escaped = SecurityElement.Escape(documentation) ?? "";
        foreach (var line in NormalizeNewlines(escaped).Split(LineFeed))
        {
            AppendLine(source, $"{indentation}/// {line}");
        }

        AppendLine(source, $"{indentation}/// </summary>");
    }

    private static string NormalizeNewlines(string value)
    {
        return value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', LineFeed);
    }

    private static void AppendLine(StringBuilder source, string value = "")
    {
        source.Append(value);
        source.Append(LineFeed);
    }
}
