using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using MyFhirSdk.CodeGen.Models;

namespace MyFhirSdk.CodeGen.Rendering;

public sealed class PrimitiveRegistryCompositionRenderer
{
    private const char LineFeed = '\n';

    public string Render(PrimitiveRegistryCompositionModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        var source = new StringBuilder();
        AppendLine(source, "// <auto-generated />");
        AppendLine(source, "#nullable enable");
        AppendLine(source);
        AppendLine(source, "using System.Collections.Generic;");
        AppendLine(source);
        AppendLine(source, $"namespace {model.Namespace};");
        AppendLine(source);
        AppendLine(source, "internal sealed partial class PrimitiveRegistry");
        AppendLine(source, "{");
        AppendLine(source, "    static partial void AddGeneratedDefinitions(");
        AppendLine(source, "        List<IPrimitiveDefinition> definitions)");
        AppendLine(source, "    {");

        var entries = model.Entries
            .OrderBy(entry => entry.FhirTypeName, StringComparer.Ordinal)
            .ToArray();
        for (var index = 0; index < entries.Length; index++)
        {
            RenderEntry(source, entries[index]);
            if (index < entries.Length - 1)
            {
                AppendLine(source);
            }
        }

        AppendLine(source, "    }");
        AppendLine(source, "}");
        return source.ToString();
    }

    private static void RenderEntry(
        StringBuilder source,
        PrimitiveRegistryEntryModel entry)
    {
        AppendLine(source, "        definitions.Add(");
        AppendLine(
            source,
            $"            Define<{entry.WrapperName}, {entry.ClrValueType}>(");
        AppendLine(
            source,
            $"                {SymbolDisplay.FormatLiteral(entry.FhirTypeName, true)},");
        AppendLine(source, $"                {entry.CodecSymbol},");
        AppendLine(source, $"                {entry.ValidatorSymbol}));");
    }

    private static void AppendLine(StringBuilder source, string value = "")
    {
        source.Append(value);
        source.Append(LineFeed);
    }
}
