using System.Text;
using MyFhirSdk.CodeGen.Metadata;

namespace MyFhirSdk.CodeGen.Rendering;

public sealed class ValidationCompositionRenderer
{
    public const string ArtifactPath = "Generated/R5/ModelMetadata/R5ValidationRules.g.cs";

    public string Render(ModelMetadataIrBatch metadata)
    {
        ArgumentNullException.ThrowIfNull(metadata);
        var source = new StringBuilder();
        AppendLine(source, "// <auto-generated />");
        AppendLine(source, "#nullable enable");
        AppendLine(source);
        AppendLine(source, "namespace MyFhirSdk.ModelMetadata.R5;");
        AppendLine(source);
        AppendLine(source, "internal static class GeneratedR5ValidationRules");
        AppendLine(source, "{");
        AppendLine(source, "    internal static global::MyFhirSdk.Validation.Rules.ResourceRuleRegistry Create() =>");
        AppendLine(source, "        global::MyFhirSdk.Validation.Rules.ResourceRuleRegistry.Create(");
        AppendLine(source, "            new global::System.Collections.Generic.KeyValuePair<");
        AppendLine(source, "                global::System.Type,");
        AppendLine(source, "                global::System.Collections.Generic.IReadOnlyList<global::MyFhirSdk.Validation.Rules.IFhirValidationRule>>[]");
        AppendLine(source, "            {");
        foreach (var type in metadata.ValidationTypes)
        {
            AppendLine(source, "                new(");
            AppendLine(source, $"                    typeof({TypeName(type.ClrType)}),");
            AppendLine(source, "                    new global::MyFhirSdk.Validation.Rules.IFhirValidationRule[]");
            AppendLine(source, "                    {");
            foreach (var rule in type.Rules)
            {
                AppendLine(source, $"                        {RenderRule(type.ClrType, rule)},");
            }
            AppendLine(source, "                    }),");
        }
        AppendLine(source, "            });");
        AppendLine(source, "}");
        return source.ToString();
    }

    private static string RenderRule(string clrType, ValidationRuleMetadataIr rule)
    {
        var type = TypeName(clrType);
        var path = Escape(rule.FhirPath);
        return rule.Kind switch
        {
            ValidationRuleKind.RequiredScalar =>
                $"global::MyFhirSdk.Validation.Rules.RequiredFieldRule<{type}>.For(\"{path}\", value => value.{rule.ClrPropertyNames.Single()})",
            ValidationRuleKind.RequiredCollection =>
                $"global::MyFhirSdk.Validation.Rules.RequiredFieldRule<{type}>.ForList(\"{path}\", value => value.{rule.ClrPropertyNames.Single()})",
            ValidationRuleKind.ChoiceAtMostOne => RenderChoice(
                "AtMostOne",
                type,
                path,
                rule.ClrPropertyNames),
            ValidationRuleKind.ChoiceExactlyOne => RenderChoice(
                "ExactlyOne",
                type,
                path,
                rule.ClrPropertyNames),
            _ => throw new ArgumentOutOfRangeException(nameof(rule))
        };
    }

    private static string RenderChoice(
        string method,
        string type,
        string path,
        IReadOnlyList<string> propertyNames) =>
        $"global::MyFhirSdk.Validation.Rules.ChoiceElementRule<{type}>.{method}(" +
        $"\"{path}\", {string.Join(", ", propertyNames.Select(name => $"value => value.{name}"))})";

    private static string TypeName(string clrType) => "global::" + clrType;

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static void AppendLine(StringBuilder source, string value = "") =>
        source.Append(value).Append('\n');
}
