using MyFhirSdk.CodeGen.Models;
using MyFhirSdk.CodeGen.Rendering;
using Xunit;

namespace MyFhirSdk.CodeGen.Tests.Rendering;

public sealed class CSharpClassRendererTests
{
    private readonly CSharpClassRenderer _renderer = new();

    [Fact]
    public void Render_ProducesDeterministicClassWithOrderedProperties()
    {
        var model = CreateModel(
            isAbstract: false,
            properties:
            [
                CreateProperty(
                    "HumanName.given",
                    "Given",
                    "MyFhirSdk.Primitives.FhirString",
                    isCollection: true,
                    documentation: "Given names.",
                    order: 1),
                CreateProperty(
                    "HumanName.family",
                    "Family",
                    "MyFhirSdk.Primitives.FhirString",
                    isCollection: false,
                    documentation: "Family <name> & \"surname\".",
                    order: 0)
            ]);

        var firstSource = _renderer.Render(model);
        var secondSource = _renderer.Render(model);

        const string expected =
            "// <auto-generated />\n" +
            "#nullable enable\n" +
            "\n" +
            "using System.Collections.Generic;\n" +
            "using MyFhirSdk.Core;\n" +
            "using MyFhirSdk.Primitives;\n" +
            "\n" +
            "namespace MyFhirSdk.GeneratorFixtures.Types;\n" +
            "\n" +
            "/// <summary>\n" +
            "/// Human-readable definition from StructureDefinition.\n" +
            "/// </summary>\n" +
            "public sealed class HumanName : DataType\n" +
            "{\n" +
            "    /// <summary>\n" +
            "    /// Family &lt;name&gt; &amp; &quot;surname&quot;.\n" +
            "    /// </summary>\n" +
            "    public FhirString? Family { get; set; }\n" +
            "\n" +
            "    /// <summary>\n" +
            "    /// Given names.\n" +
            "    /// </summary>\n" +
            "    public IList<FhirString> Given { get; set; } = new List<FhirString>();\n" +
            "}\n";

        Assert.Equal(expected, firstSource);
        Assert.Equal(firstSource, secondSource);
        Assert.DoesNotContain('\r', firstSource);
        Assert.False(firstSource.StartsWith('\uFEFF'));
    }

    [Fact]
    public void Render_WithAbstractModelAndMultilineDocumentation_UsesAbstractClass()
    {
        var model = CreateModel(
            isAbstract: true,
            properties:
            [
                CreateProperty(
                    "HumanName.period",
                    "Period",
                    "MyFhirSdk.Types.Period",
                    isCollection: false,
                    documentation: "First line.\r\nSecond line's detail.",
                    order: 0)
            ]);

        var source = _renderer.Render(model);

        Assert.Contains(
            "using MyFhirSdk.Core;\nusing MyFhirSdk.Types;\n",
            source,
            StringComparison.Ordinal);
        Assert.Contains(
            "public abstract class HumanName : DataType",
            source,
            StringComparison.Ordinal);
        Assert.Contains(
            "    /// First line.\n    /// Second line&apos;s detail.\n",
            source,
            StringComparison.Ordinal);
        Assert.Contains(
            "    public Period? Period { get; set; }",
            source,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Render_WithNullModel_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => _renderer.Render(null!));
    }

    private static FhirTypeModel CreateModel(
        bool isAbstract,
        IEnumerable<FhirPropertyModel> properties)
    {
        return new FhirTypeModel(
            fhirName: "HumanName",
            cSharpName: "HumanName",
            @namespace: "MyFhirSdk.GeneratorFixtures.Types",
            cSharpBaseType: "MyFhirSdk.Core.DataType",
            isAbstract: isAbstract,
            sourceCanonical: "http://hl7.org/fhir/StructureDefinition/HumanName",
            sourceVersion: "5.0.0",
            properties: properties);
    }

    private static FhirPropertyModel CreateProperty(
        string elementId,
        string cSharpName,
        string cSharpType,
        bool isCollection,
        string? documentation,
        int order)
    {
        return new FhirPropertyModel(
            elementId: elementId,
            elementPath: elementId,
            fhirName: char.ToLowerInvariant(cSharpName[0]) + cSharpName[1..],
            cSharpName: cSharpName,
            cSharpType: cSharpType,
            cardinality: new CardinalityModel(
                min: 0,
                max: isCollection ? "*" : "1",
                isCollection: isCollection,
                isRequired: false),
            documentation: documentation,
            order: order);
    }
}
